### PR TITLE
This changes the issue templates used.

### PR DESCRIPTION
**Pull request by TheIntolerant**
These form templates are made with GitHub's form schema, which is currently in beta.

They will ensure people provide the necessary information needed in bug reports etc. It should also help decrease the frequency that questions like "Are you using MySQL?" need to be asked or statements like "Please make sure you are using the latest version of the plugin" need to be made.

This setup also makes the information shown here https://github.com/kangarko/ChatControl-Red/issues/1389 redundant as that information can now be directly provided in these new templates.

### CODE REVIEW

**Comment by ElBananaa** [comment]
That would be pretty useful and more user-friendly!
Could you add a part for ProtocolLib? So we can also know if the user has ProtocolLib installed, and which ProtocolLib version is installed if that's the case (I believe using `/version ProtocolLib` give us the exact build number)

This would be more precise than simply asking them if they use the very latest version of the plugin and its dependencies, as we've encountered many users telling us they are while they actually used an older version/dev build.

**Comment by TheIntolerant** [comment]
Done

**Comment by kangarko** [comment]
Interesting and very useful, thanks to both of you guys! You have been helping us a lot so I understand how frustrating is dealing with improperly filled tickets. Thanks for such a great suggestion Ezra :)

**Comment by kangarko** [comment]
I removed the checkbox "Yes I am using the latest version" since I personally find it annoying as well as made the templates shorter a bit.

If you have any suggestions or you notice that people still abuse / not use it properly then just let me know!

**Pull request merged**
