### PR TITLE
Update bug_report.yml

### PR DESCRIPTION
**Pull request by ElBananaa**
Ensure players use an updated version of the plugin before submitting a bug.

### CODE REVIEW

**Comment by kangarko** [comment]
How is this a problem? I know it was in the original pull request that @TheIntolerant posted but I find it annoying myself when I want to submit a simple ticket on a website and I have to click through dumb "I am using the latest version" buttons. I don't think it solves the problem.

**Comment by TheIntolerant** [comment]
I added it, because I found people every so often reported issues which had already been resolved, which is why I thought it would be useful.

**Comment by ElBananaa** [comment]
@kangarko this is used to remind users to update the plugin before reporting anything.
We've had too many users reporting issues without providing their debug log claiming the plugin is up to date. Ans we always found out a few days later when they finally provide their debug files that they actually didn't use the latest update.

So this is a simple click that will, in most cases, make users lose 2 seconds of their time, compared to issues that will usually take hours or even days to be solved because of an outdated plugin version.

Ofc some users will check that without even reading what it says, but it'll be a minority.

Btw, I added this thing back because Intolerant did (once again) answer to an issue caused by an outdated plugin version yesterday.

**Comment by kangarko** [comment]
No worries, I have pulled it! :)

**Pull request merged**
